"""Initial migration

Revision ID: 071052e4f053
Revises: 
Create Date: 2025-06-21 02:07:27.875861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '071052e4f053'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('joueur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pseudo', sa.String(length=50), nullable=False),
    sa.Column('nom_complet', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pseudo')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tournoi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('jeu', sa.String(length=100), nullable=False),
    sa.Column('date_debut', sa.DateTime(), nullable=False),
    sa.Column('date_fin', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournoi_id', sa.Integer(), nullable=False),
    sa.Column('joueur1_id', sa.Integer(), nullable=False),
    sa.Column('joueur2_id', sa.Integer(), nullable=False),
    sa.Column('score_joueur1', sa.Integer(), nullable=True),
    sa.Column('score_joueur2', sa.Integer(), nullable=True),
    sa.Column('date_match', sa.DateTime(), nullable=False),
    sa.Column('termine', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['joueur1_id'], ['joueur.id'], ),
    sa.ForeignKeyConstraint(['joueur2_id'], ['joueur.id'], ),
    sa.ForeignKeyConstraint(['tournoi_id'], ['tournoi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournoi_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['tournoi_id'], ['tournoi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prix')
    op.drop_table('match')
    op.drop_table('tournoi')
    op.drop_table('user')
    op.drop_table('joueur')
    # ### end Alembic commands ###
